name=PipeGIF
version=1.0.0
author=Hans Schou <h.ansschou@gmail.com>
maintainer=Hans Schou <h.ansschou@gmail.com>
sentence=GIF decoder piping data from one program to another
paragraph=Decoding GIF data without having a file. Data can come from anywhere like internal constant data or network. The receiving display has to be defined as a C++ class according to the hardware.
url=https://github.com/fun6400/PipeGIF
